<?php

/**
 * Created by PhpStorm.
 * User: Schneidoa
 * Date: 13.06.16
 * Time: 23:51
 */
namespace Schneidoa\EasyAnnotation;

class EasyAnnotationClass extends \ReflectionClass
{

    public function __construct($argument)
    {
        parent::__construct($argument);
    }

    public function getProperty($name)
    {
        parent::getProperty($name); // TODO: Change the autogenerated stub

        return new EasyAnnotationProperty($this->getName(), $name);
    }

    
}
